FROM node:18

WORKDIR /usr/easypay

RUN apt-get update && apt-get install -y wget \
    && wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz \
    && rm dockerize-linux-amd64-v0.6.1.tar.gz

COPY package.json yarn.lock prisma ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build
